### ISSUE TITLE
Non-US events have duplicate and/or wrong locations

### ISSUE THREAD

**Issue by bananabrann** [ryanburgess/2020-conferences#4]
When an event is not in the United States, the event's "Where" column is glitched.

Examples:
Oslo Elm Day, 16 - 16 February, 2020, **Norway, Oslo, Norway**
HolyJS Piter 10 - 11 April, 2020, **Russian Federation, Saint Petersburg, Russia**
ReactNext 9 - 10 June, 2020, **Iran, Islamic Republic of, Tel Aviv, Isreal**

**Comment by ryanburgess** [comment]
That was weird. Thank you for opening the issue. I've fixed the issue.
